import type { Metadata } from "next";
import { Inter } from "next/font/google";
// فایل CSS قبلی را حذف یا کامنت کرده و فایل Sass را اضافه کنید
// import './globals.css';
import "../styles/main.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
